# Generated by Django 6.0.5 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_nome_completo_contato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_contatos/'),
        ),
    ]
